---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .rolling_deploy_pipeline
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: toolchain
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: cra
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: devops-insights
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: tester
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: utils
triggers:
  - type: git
    name: rolling-commit-push
    eventListener: rolling-${GIT_COMMIT_EVENT_LISTENER_NAME}
    service: ${INVENTORY_REPO}
    branch: ${APP_REPO_BRANCH}
    events: { "push": true }
  - type: manual
    name: rolling-manual-run
    eventListener: rolling-manual-run
    properties:
      - name: branch
        type: text
        value: ${APP_REPO_BRANCH}              
properties:
  - name: apikey
    value: ${API_KEY}
    type: SECURE
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: artifactory
    value: ${ARTIFACTORY}
    type: Integration     
  - name: cos-bucket-name
    value: ${COS_BUCKET_NAME}
    type: text
  - name: cos-api-key
    value: ${COS_API_KEY}
    type: SECURE
  - name: target
    value: ${TARGET}
    type: text
  - name: deployment-strategy
    value: ${DEPLOYMENT_STRATEGY}
    type: text
  - name: lb-pool
    value: ${ROLLING_POOL}  
    type: text
  - name: loadbalancer
    value: ${LOADBALANCER}
    type: text
  - name: bastion-host
    value: ${VIRTUAL_SERVER_INSTANCE}
    type: text
  - name: region
    value: ${REGION}
    type: text   
  - name: bastion-host-user-name
    value: ${BASTION_HOST_USER_NAME}
    type: text
  - name: bastion-host-ssh-keys
    value: ${BASTION_HOST_SSH_KEYS}
    type: SECURE    
  - name: pool-user-name
    value: ${BASTION_HOST_USER_NAME}
    type: text 
  - name: pool-ssh-keys
    value: ${BASTION_HOST_SSH_KEYS}
    type: SECURE
  - name: inventory-repo
    value: ${INVENTORY_REPO}
    type: integration
    path: parameters.repo_url
  - name: scripts-repo
    value: ${APP_REPO}
    type: integration
    path: parameters.repo_url    
  - name: insights
    value: ${INSIGHTS}
    type: integration
    path: service_id
  - name: scripts-repo-branch
    type: text
    value: 'master'
  - name: inventory-repo-branch
    type: text
    value: "master"
  - name: scripts-subpath
    type: text
    value: 'scripts'
  - name: commons-hosted-region
    value: ${COMMONS_HOSTED_REGION}
    type: text     