---
inputs:
  - type: git
    branch: ${PIPELINE_REPO_BRANCH}
    service: ${PIPELINE_REPO}
    path: .pr_pipeline
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: git
  - type: git
    service: ${TEKTON_CATALOG_REPO}
    branch: ${DEFINITIONS_BRANCH}
    path: toolchain
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: cra
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: linter
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: tester
  - type: git
    branch: ${DEFINITIONS_BRANCH}
    service: ${TEKTON_CATALOG_REPO}
    path: utils
triggers:
  - type: git
    name: Git PR Trigger
    service: ${APP_REPO}
    branch: ${APP_REPO_BRANCH}
    events:
      pull_request: true
    eventListener: ${GIT_COMMIT_EVENT_LISTENER_NAME}
properties:
  - name: apikey
    value: ${API_KEY}
    type: SECURE
  - name: git-token
    type: secure
  - name: pipeline-debug
    value: "0"
    type: text
  - name: repository
    value: ${APP_REPO}
    type: Integration
    path: parameters.repo_url
  - name: insights
    value: ${INSIGHTS}
    type: integration
    path: service_id
  - name: region
    value: ${REGION}
    type: text  
  - name: scripts-repo
    value: ${APP_REPO}
    type: integration
    path: parameters.repo_url
  - name: scripts-repo-branch
    type: text
    value: 'master'
  - name: scripts-subpath
    type: text
    value: 'scripts'    
