---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: ibmcloud-api
      description: The ibmcloud api
    - name: git-token
      description: access token for the git repo
    - name: ibmcloud-region
      description: (Optional) ibmcloud region to use
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline
    - name: registry-region
      description: (Optional) The ibmcloud container registry region
    - name: resource-group
      description: (Optional) Target resource group (name or id) for the ibmcloud login operation  
    # Event params
    - name: branch
      description: The git branch
    - name: commit-id
      description: the git revision/commit for the git repo source
      default: "" 
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
    - name: pr-repository
      description: The forked git repo from where the PR is made
    - name: repository
      description: The git repo
    - name: scripts-subpath
      description: The subpath to the script repo from root
    - name: scripts-repo
      description: The variable storing git integration for the repository storing build and deploying source code
    - name: scripts-repo-branch
      description: The branch of the scripts-repo
    - name: toolchain-build-image
      description: Image to use for `build` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46"
    - name: tester-tests-image
      description: Image to use for `unit-test` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46"

  workspaces:
    - name: pipeline-ws  
  tasks:
    - name: git-clone-application-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: git-access-token
          value: $(params.git-token)
        - name: pr-branch
          value: $(params.pr-branch)
        - name: pr-repository
          value: $(params.pr-repository)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.commit-id)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: git-clone-scripts-repo
      taskRef:
        name: git-clone-repo
      runAfter:
        - git-clone-application-repo    
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(params.scripts-repo)
        - name: branch
          value: $(params.scripts-repo-branch) 
        - name: revision
          value: $(params.scripts-repo-branch) 
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: git-credentials-json-file
          value: credentials.json          
      workspaces:
        - name: output
          workspace: pipeline-ws
          subpath: scripts-repo    
    - name: build
      runAfter: [git-clone-scripts-repo]
      taskRef:
        name: toolchain-build
      params:
        - name: run-build-image
          value: $(params.toolchain-build-image)
        - name: custom-script
          value: |
            #!/bin/bash
            # Your build script should go here.
            # Existing template utilizes a Maven Based Java Application and hence the build steps utilizes maven mvn wrapper to build the Java Archive
            # In case your application is Java/Go based where the deployment unit comprises of a binary you may need to modify the lines below to cater
            # to the needs of your build system. For interpreter based project (Python/JS), where the application needs only the source code, you may
            # skip this step or comment out the existing lines and move over to copy the contents to /artifacts/binaries folder.            
            echo "Running Application Source Code Build Script"
            subpath="$(params.scripts-subpath)"
            source ./scripts-repo/${subpath}/build.sh
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: unit-tests
      runAfter: [build]
      taskRef:
        name: tester-run-tests
      params: 
        - name: tests-image
          value: $(params.tester-tests-image)
        - name: tests-script
          value: |
            #!/bin/bash            
            echo "Running Unit Test Script"
            subpath="$(params.scripts-subpath)"
            source ./scripts-repo/${subpath}/unit-tests.sh
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
