---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: branch
      description: branch
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: pr-url
      description: pr url
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: commit-timestamp
    - name: scm-type
    - name: project-id
      default: ""
    - name: toolchain-region 
    - name: runtime
      description: The variable storing language runtime 
    - name: pipeline-repo
      description: The variable storing git integration for the repository storing build pipeline code for the toolchain      
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: git-clone-application-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: git-clone-pipeline-repo
      taskRef:
        name: git-clone-repo
      runAfter:
        - git-clone-application-repo    
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(params.pipeline-repo)
        - name: branch
          value: "master"
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: git-credentials-json-file
          value: credentials.json          
      workspaces:
        - name: output
          workspace: pipeline-ws
          subpath: pipeline-repo    
    - name: unit-tests
      runAfter: [git-clone-pipeline-repo]
      taskRef:
        name: tester-run-tests
      params: 
        - name: tests-script
          value: |
            #!/bin/bash            
            echo "Running Unit Test Script"
            source ./pipeline-repo/scripts/$(params.runtime)/unit-tests.sh
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
    - name: cra-discovery-scan
      when:
        - input: "$(params.toolchain-region)"
          operator: in
          values: [ "ibm:yp:us-south" , "ibm:yp:us-east" ]    
      runAfter:
        - git-clone-application-repo
      taskRef:
        name: cra-discovery
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.branch)
        - name: commit-id
          value: $(tasks.git-clone-application-repo.results.git-commit)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: directory-name
          value: ""
        - name: commit-timestamp
          value: $(params.commit-timestamp)
    - name: code-vulnerability-status-pending
      runAfter:
        - git-clone-application-repo
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: pending
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "Vulnerability scan"
        - name: repository
          value: $(params.repository)
    - name: code-vulnerability-scan
      runAfter:
        - cra-discovery-scan
      taskRef:
        name: cra-vulnerability-remediation
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
        - name: secrets
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.repository)
        - name: source-repository
          value: $(tasks.git-clone-application-repo.results.git-repository)
        - name: revision
          value: $(params.branch)
        - name: pr-url
          value: $(params.pr-url)
        - name: commit-id
          value: $(tasks.git-clone-application-repo.results.git-commit)
        - name: scm-type
          value: $(params.scm-type)
        - name: project-id
          value: $(params.project-id) 
    - name: code-vulnerability-scan-status-finished
      runAfter:
        - code-vulnerability-scan
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.repository)
        - name: state
          value: "$(tasks.code-vulnerability-scan.results.status)"
        - name: context
          value: "Vulnerability scan"
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: code-cis-scan-status-pending
      runAfter:
        - git-clone-application-repo
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: pending
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "CIS scan"
        - name: repository
          value: $(params.repository)
    - name: cra-cis-check
      taskRef:
        name: cra-cis-check
      runAfter:
        - cra-discovery-scan
      workspaces:
        - name: secrets
          workspace: pipeline-ws
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.repository)
        - name: source-repository
          value: $(tasks.git-clone-application-repo.results.git-repository)
        - name: revision
          value: $(params.branch)
        - name: pr-url
          value: $(params.pr-url)
        - name: commit-id
          value: $(tasks.git-clone-application-repo.results.git-commit)
        - name: directory-name
          value: ""
        - name: scm-type
          value: $(params.scm-type)
        - name: project-id
          value: $(params.project-id)
    - name: code-cis-scan-status-finished
      runAfter:
        - cra-cis-check
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: "$(tasks.cra-cis-check.results.status)"
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "CIS scan"
        - name: repository
          value: $(params.repository)
    - name: code-bom-check-status-pending
      runAfter:
        - git-clone-application-repo
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: pending
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "BOM check"
        - name: repository
          value: $(params.repository)
    - name: cra-bom
      taskRef:
        name: cra-bom
      runAfter:
        - cra-discovery-scan
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
        - name: secrets
          workspace: pipeline-ws          
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.branch)
        - name: pr-url
          value: $(params.pr-url)
        - name: commit-id
          value: $(tasks.git-clone-application-repo.results.git-commit)
        - name: target-branch
          value: $(params.branch)
        - name: target-commit-id
          value: $(tasks.git-clone-application-repo.results.git-commit)      
        - name: scm-type
          value: $(params.scm-type)
        - name: project-id
          value: $(params.project-id)
        - name: source-repository
          value: $(tasks.git-clone-application-repo.results.git-repository)
    - name: code-bom-check-status-finished
      runAfter:
        - cra-bom
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: "$(tasks.cra-bom.results.status)"
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "BOM check"
        - name: repository
          value: $(params.repository)      
          