apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: download-artifacts
spec:
  params:
    - name: api
      description: the IBM Cloud api endpoint
      default: "https://cloud.ibm.com"
    - name: apikey
      description: The IBM Cloud API Key
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
      default: region
    - name: artifactory
      description: The variable storing artifactory integration with the toolchain
    - name: cos-api-key
      description: The API Key to interact with the Cloud Object Storage Instance
    - name: cos-bucket-name
      description: The Cloud Object Storage Bucket name where build artifact will be stored.
  workspaces:
    - name: output
      description: A workspace
      mountPath: /output
  results:
    - name: artifacts-downloaded
      description: The variable indicating whether artifact is downloaded or not
    - name: build_number
      description: The variable storing build number as retrieved from the build metadata
    - name: objectname
      description: The name of the build artifact as retrieved from the build metadata
  steps:
    - name: download-artifacts
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
      workingDir: /output
      env:
        - name: API
          value: $(params.api)
        - name: APIKEY
          value: $(params.apikey)
        - name: ARTIFACTORY
          value: $(params.artifactory)
        - name: COSBUCKETNAME
          value: $(params.cos-bucket-name)
        - name: COSAPIKEY
          value: $(params.cos-api-key)
        - name: FILE
          value: inventory.json
        - name: REGION
          value: $(params.region)            
      script: |
          #!/bin/bash

          # Code here fetches the artifact metadata as present in the inventory.json.
          # The task assumes the file /output/inventory-repo/inventory.json is already present as a result of the cloning of the 
          # by the upstream git-clone-inventory-repo task. The JSON file contains the metadata like the name of the name of the artifact (artifact)
          # the build number (build_number) among other details. 
          
          cd /output/inventory-repo;          
          if [[ -f "$FILE" ]]; then
            OBJECTNAME=$(cat $FILE |jq -r '.artifact')
            BUILD=$(cat $FILE |jq -r '.build_number')
            echo -n "${BUILD}" > $(results.build_number.path)
            echo -n "${OBJECTNAME}" > $(results.objectname.path)
          fi

          # Code here downloads the artifact after processing the information present in the inventory.json.
          # The downloaded artifacts will be stored in /output directory which can then be utilized by downstream
          # task to carry out deployment steps on the target Virtual Server instance.
          cd /output
          if [ -z ${COSAPIKEY} ]; then echo "COSAPIKEY is not set"; COSAPIKEY=$APIKEY; fi;
          #
          # Function to download the binary artifact from IBM Cloud Object Store
          # 
          DownloadFromCOS() {
            echo "Check if the Bucket with name $COSBUCKETNAME exists"
            ibmcloud login -a $API -r $REGION --apikey $COSAPIKEY;
            ibmcloud plugin install cloud-object-storage;           
            if ibmcloud cos bucket-location-get --bucket $COSBUCKETNAME 2>/dev/null ; then
              REGION=$(ibmcloud cos bucket-location-get --bucket $COSBUCKETNAME | grep -i REGION | awk {'print $2'})
              ibmcloud login -a $API -r $REGION --apikey $COSAPIKEY;
              echo "Started downloading of artifacts from IBM Cloud Object Storage"
              ibmcloud cos object-get --bucket "$COSBUCKETNAME" --key ${OBJECTNAME} ${OBJECTNAME}
              echo "Finished downloading of artifacts from IBM Cloud Object Storage"
            else
              echo "Invalid cos-bucket-name for retreving artifacts"
              exit 1;
            fi
          }

          #
          # Function to download the binary artifact from Artifactory
          # 
          DownloadFromArtifactory() {
            USERID=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.user_id')
            TOKEN=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.token')
            REPO=$(echo "$ARTIFACTORY" | jq -r '.parameters' | jq -r '.release_url')
            echo "Started downloading of artifacts from Artifactory"
            curl -u $USERID:$TOKEN "$REPO/$OBJECTNAME" --output $OBJECTNAME
            echo "Finished downloading of artifacts from Artifactory"
          }

          #
          # Driver Function to download the binary artifact
          # The function:
          #   Checks if the Artifactory Integration exists. If yes then it downloads the artifacts from Artifactory.
          #   If no then it downloads the artifacts from IBM Cloud Object Storage.
          # 
          if [ -n "$ARTIFACTORY" ]; then
            if jq -e . >/dev/null 2>&1 <<<"$ARTIFACTORY"; then
              echo "Artifactory Configuration found in the toolchain."
              DownloadFromArtifactory
            else
              echo "Artifactory Configuration not found in the toolchain. Proceeding with Cloud Object Storage."
              DownloadFromCOS
            fi
          else
            echo "Artifactory Configuration not found in the toolchain. Proceeding with Cloud Object Storage."
            DownloadFromCOS
          fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
      default: region
    - name: api
      description: the IBM Cloud api endpoint
      default: "https://cloud.ibm.com"
    - name: apikey
      description: The IBM Cloud API Key
    - name: artifactory
      description: The variable storing artifactory integration with the toolchain
    - name: appname
      description: The name of the application passed as environment variable
    - name: cos-bucket-name
      description: The Cloud Object Storage Bucket name where build artifact will be stored.
    - name: inventory-repo
      description: The variable storing git integration for the repository storing build inventory with the toolchain
    - name: objectname
      description: The name of the build artifact
    - name: scripts-subpath
      description: The application lanugage scripts-subpath
    - name: bastion-host
      description: Bastion Host virtual-server-instance
    - name: bastion-host-user-name
      description: Bastion Host User Name
    - name: bastion-host-ssh-keys
      description: Bastion host 
    - name: lb-pool
      description: Load Balancer Pool
    - name: deployment-strategy
      description: Deployemnt Strategy
    - name: loadbalancer
      description: Load Balancer Name
    - name: pool-ssh-keys
      description: Blue and Green Pool base64 encoded private SSH key 
    - name: pool-user-name   
      description: Blue and Green Pool User Name
    - name: instance-group-1
    - name: instance-group-2
    - name: canary-step-size
    - name: canary-step-interval
    - name: commons-hosted-region
      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"                       
  workspaces:
    - name: output
      description: A workspace
      mountPath: /output
  steps:
    - name: deploy
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
      workingDir: /output
      env:
        - name: REGION
          value: $(params.region)
        - name: API
          value: $(params.api)
        - name: APIKEY
          value: $(params.apikey)
        - name: ARTIFACTORY
          value: $(params.artifactory)
        - name: APPNAME
          value: $(params.appname)
        - name: COSBUCKETNAME
          value: $(params.cos-bucket-name)
        - name: INVENTORY_REPO
          value: $(params.inventory-repo)
        - name: OBJECTNAME
          value: $(params.objectname)
        - name: scripts-subpath
          value: $(params.scripts-subpath)
        - name: FILE
          value: inventory.json
        - name: BASTION_HOST
          value: $(params.bastion-host)
        - name: BASTION_HOST_USER_NAME
          value: $(params.bastion-host-user-name)        
        - name: BASTION_HOST_SSH_KEYS
          value: $(params.bastion-host-ssh-keys)      
        - name: LB_POOL
          value: $(params.lb-pool)                          
        - name: LOAD_BALANCER_NAME
          value: $(params.loadbalancer)                   
        - name: DEPLLOYMENT_STRATEGY
          value: $(params.deployment-strategy)                
        - name: POOL_SSH_KEYS
          value: $(params.pool-ssh-keys)         
        - name: POOL_USER_NAME
          value: $(params.pool-user-name) 
        - name: INSTANCE_GROUP_1
          value: $(params.instance-group-1)
        - name: INSTANCE_GROUP_2
          value: $(params.instance-group-2)
        - name: STEP_SIZE
          value: $(params.canary-step-size)
        - name: STEP_INTERVAL
          value: $(params.canary-step-interval)
        - name: COMMON_HOSTED_REGION
          value: $(params.commons-hosted-region)                                
      script: |
        #!/bin/bash
        # This step logs into the Virtual Server Instance based on the credentials provided during the Toolchain creation.
        # The step: 
        #   - Assumes that the upstream task has already downloaded the artifact to the /output location 
        #   - Carries out all the operation within the home directory of the user i.e. /home/${HOST_USER_NAME}
        #   - Copies the artifact from the /output to /home/${HOST_USER_NAME}/app which is defined as WORKDIR
        #   - Runs the deploy.sh file as created in the previous step to carry out the step-by-step deployment which may include start/stop of application.
        cd /output/inventory-repo;          
        if [[ -f "$FILE" ]]; then
          PIPELINERUNID=$(cat $FILE |jq -r '.pipeline_run_id')
        fi
        cd /output
        WORKDIR=/home/${BASTION_HOST_USER_NAME}/app
        BACKUPDIR=${WORKDIR}_backup
        subpath="$(params.scripts-subpath)"
        source <(curl -sSL "$COMMON_HOSTED_REGION/scripts/deployment_strategies/canary/vsi/setup-remote-deploy-canary.sh")
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: release
spec:
  params:
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
      default: region
    - name: api
      description: the IBM Cloud api endpoint
      default: "https://cloud.ibm.com"
    - name: apikey
      description: The IBM Cloud API Key  
    - name: scripts-subpath
      description: The subpath to the script repo from root
    - name: lb-pool
      description: Blue Pool for Blue Green Deployemnt
    - name: loadbalancer
      description: Load Balancer Name
    - name: deployment-strategy
      description: Deployment Strategy
    - name: instance-group-1
    - name: instance-group-2
    - name: canary-step-size
    - name: canary-step-interval
    - name: commons-hosted-region
      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"                        
  workspaces:
    - name: output
      description: A workspace
      mountPath: /output  
  steps:
    - name: release
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
      workingDir: /output
      env:
        - name: REGION
          value: $(params.region)
        - name: API
          value: $(params.api)
        - name: APIKEY
          value: $(params.apikey)      
        - name: scripts-subpath
          value: $(params.scripts-subpath)      
        - name: LB_POOL
          value: $(params.lb-pool)                         
        - name: LOAD_BALANCER_NAME
          value: $(params.loadbalancer)
        - name: DEPLLOYMENT_STRATEGY
          value: $(params.deployment-strategy)
        - name: INSTANCE_GROUP_1
          value: $(params.instance-group-1)
        - name: INSTANCE_GROUP_2
          value: $(params.instance-group-2)
        - name: STEP_SIZE
          value: $(params.canary-step-size)
        - name: STEP_INTERVAL
          value: $(params.canary-step-interval)
        - name: COMMON_HOSTED_REGION
          value: $(params.commons-hosted-region)                                                              
      script: |
        #!/bin/bash
        cd /output
        WORKDIR=/home/${BASTION_HOST_USER_NAME}/app
        BACKUPDIR=${WORKDIR}_backup
        subpath="$(params.scripts-subpath)"
        source <(curl -sSL "$COMMON_HOSTED_REGION/scripts/deployment_strategies/canary/vsi/canary-test.sh")
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-doi-deployrecord
spec:
  params:
    - name: inventory-repo
      description: The variable storing git integration for the repository storing build inventory with the toolchain
    - name: api
      description: The IBM Cloud API Endpoint
    - name: apikey
      description: The IBM Cloud API Key
    - name: appname
      description: The name of the application passed as environment variable
    - name: target
      description: The name of the environment where deployment needs to be performed
    - name: build_number
      description: The build number of the build as retreived from the build metadata
  workspaces:
    - name: output
      description: A workspace to store the output of intermittent steps
      mountPath: /output
  volumes:
    - name: cd-config
      configMap:
        name: toolchain
  steps:
    - name: publish-doi-deployrecord
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
      volumeMounts:
        - name: cd-config
          mountPath: /cd-config
      workingDir: /artifacts
      env:
        - name: API
          value: $(params.api)
        - name: APIKEY
          value: $(params.apikey)
        - name: APP_NAME
          value: $(params.appname)
        - name: TOOLCHAIN_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/toolchain-id']
        - name: DEPLOY_STATUS
          value: "pass"
        - name: TARGET
          value: $(params.target)
        - name: INVENTORY_REPO
          value: $(params.inventory-repo)
        - name: JOB_URL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
        - name: BUILD_NUMBER
          value: $(params.build_number)
      script: |
        #!/bin/bash
        set -e -o pipefail
        export HOME="/root"
        TOOLCHAIN_ID=$(jq -r '.toolchain_guid' /cd-config/toolchain.json)
        export TOOLCHAIN_ID=${TOOLCHAIN_ID} # for doi plugin
        ibmcloud login -a $API --apikey $APIKEY --no-region
        ibmcloud doi publishdeployrecord --env "${TARGET}" --status=${DEPLOY_STATUS} --joburl="${JOB_URL}" \
          --buildnumber="${BUILD_NUMBER}" --logicalappname="${APP_NAME}" ${INVENTORY_REPO}
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: abort-canary
spec:
  params:
    - name: region
      description: The IBM Cloud Region in which Virtual Server Instance is running
      default: region
    - name: api
      description: the IBM Cloud api endpoint
      default: "https://cloud.ibm.com"
    - name: apikey
      description: The IBM Cloud API Key  
    - name: scripts-subpath
      description: The subpath to the script repo from root
    - name: lb-pool
      description: Blue Pool for Blue Green Deployemnt
    - name: loadbalancer
      description: Load Balancer Name
    - name: deployment-strategy
      description: Deployment Strategy
    - name: instance-group-1
    - name: instance-group-2
    - name: canary-step-size
    - name: canary-step-interval
    - name: commons-hosted-region
      default: "https://raw.githubusercontent.com/open-toolchain/commons/master"                        
  workspaces:
    - name: output
      description: A workspace
      mountPath: /output  
  steps:
    - name: abort-canary
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.46
      workingDir: /output
      env:
        - name: REGION
          value: $(params.region)
        - name: API
          value: $(params.api)
        - name: APIKEY
          value: $(params.apikey)      
        - name: scripts-subpath
          value: $(params.scripts-subpath)      
        - name: LB_POOL
          value: $(params.lb-pool)                         
        - name: LOAD_BALANCER_NAME
          value: $(params.loadbalancer)
        - name: DEPLLOYMENT_STRATEGY
          value: $(params.deployment-strategy)
        - name: INSTANCE_GROUP_1
          value: $(params.instance-group-1)
        - name: INSTANCE_GROUP_2
          value: $(params.instance-group-2)
        - name: STEP_SIZE
          value: $(params.canary-step-size)
        - name: STEP_INTERVAL
          value: $(params.canary-step-interval)
        - name: COMMON_HOSTED_REGION
          value: $(params.commons-hosted-region)                                                               
      script: |
        #!/bin/bash
        cd /output
        WORKDIR=/home/${BASTION_HOST_USER_NAME}/app
        BACKUPDIR=${WORKDIR}_backup
        subpath="$(params.scripts-subpath)"
        source <(curl -sSL "$COMMON_HOSTED_REGION/scripts/deployment_strategies/canary/vsi/abort-canary.sh")